name: Indexing search
on:
  workflow_dispatch:
  schedule:
    # 01.00 & 12.00 every day
    - cron: "00 01,12 * * *"

jobs:
  searchcrawl:
    name: Crawler nettside for søk-indeksering
    runs-on: ubuntu-latest
    env:
      APPLICATION_ID: ${{ secrets.ALGOLIA_ID}}
      API_KEY: ${{ secrets.ALGOLIA_ADMIN }}
      CONFIG: cat ./crawler/config.json | jq -r tostring
    steps:
      - name: Algolia Docsearch Action
        id: algolia
        uses: adapttive/algolia-docsearch-action@1.1.1
